### ISSUE TITLE
Directory Naming Issue with non-patreon release (v1.6.3)

### ISSUE THREAD

**Issue by JohnConfidence** [2006rs/singleplayer#14]
The user `MelloFello#3761` in the discord server discovered that when running the non-patreon client under Ubuntu (Linux), he receives the following error:
```java
➜  Server java -Xmx512m -jar Server.jar 
[9/18/19 9:19 AM]: Starting RuneScape on /0.0.0.0:43594...
[9/18/19 9:19 AM]: Read Error: ./Data/npcs/Npc drops.dat
java.lang.NullPointerException
	at com.rs2.util.F.c(Unknown Source)
	at com.rs2.model.c.a.a.a(Unknown Source)
	at com.rs2.Server.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)
```
Indicating that there is still a naming issue in the 1.6.3 release of the Server.

**Comment by Mige5** [comment]
Yea, as it was fixed on patch 1.6.4. (so 1.6.3 still has the issue)
